# Site settings
title: Andersen Gadel Wedding | April 30th, 2016
email: wandersen02@gmail.com
description: >
  The wedding site for Wyatt Andersen and Caitlin Gadel.
  To be married April 30th, 2016 at Pax Christi, reception at Mason's to follow.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.happilyeverandersen.com/" # the base hostname & protocol for your site
# Open Graph Data:
og_type: "website"
og_image: "http://www.happilyeverandersen.com/assets/images/og_photo.jpg"
og_url: "http://www.happilyeverandersen.com/"

twitter_username: wandersen02
github_username:  lostphilosopher

# Build settings
markdown: kramdown
